language: node_js

jobs:
  include:
    - stage: tests      
      script: 
        - npm run test 
    - stage: deploy      
      # only run 1 script here to make sure it all runs together. 
      script: rm .gitignore; npm run build; npx semantic-release;

stages:
  - name: tests # Run tests on every commit to help keep tests passing as long as possible.
    if: type IN (pull_request, push) AND tag IS blank # Testing on pull requests assert that after merge, the branch wont be broken.
  - name: deploy
    if: type IN (push) AND branch = master